<?php

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function pure_preview_node_view(array &$build, \Drupal\node\Entity\Node $node, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  if( $view_mode === 'default' ) {
    if( $node->in_preview ) {
      $build['#theme']='pp';
    }
  }
}

/**
 * Implements hook_theme().
 */
function pure_preview_theme($existing, $type, $theme, $path) {
  return array(
    'pp' => array(
      'variables' => array('body_content' => NULL),
    )
  );
}

/**
 * Implements hook_preprocess_HOOK().
 */
function pure_preview_process_pp(&$variables) {
}

function template_process_pp(&$variables) {
  $node = $variables['elements']['#node'];
  $variables['body_content'] = $node->get('body')->value;
}
